---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Build Bootstrap ISOs
      include_role:
        name: bootstrap_kvm
      loop: '{{ vnfs }}'
      loop_control:
        loop_var: vnf
